// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwKXGG0PFwYdr0N8iTWIcKzL726UfinxY',
    appId: '1:452055289306:web:a2da28fbcbdeb75354c4e3',
    messagingSenderId: '452055289306',
    projectId: 'babycare-86997',
    authDomain: 'babycare-86997.firebaseapp.com',
    storageBucket: 'babycare-86997.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmjXnsl2oE9Z7xGX6vT-PkKWvsK9_ZNaU',
    appId: '1:452055289306:android:51408bc636165a6354c4e3',
    messagingSenderId: '452055289306',
    projectId: 'babycare-86997',
    storageBucket: 'babycare-86997.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxFvj4z6iPEJWd0wLr7od-WzYOnHrKVGo',
    appId: '1:452055289306:ios:3af2ea3b081442a054c4e3',
    messagingSenderId: '452055289306',
    projectId: 'babycare-86997',
    storageBucket: 'babycare-86997.appspot.com',
    iosBundleId: 'com.example.babycare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxFvj4z6iPEJWd0wLr7od-WzYOnHrKVGo',
    appId: '1:452055289306:ios:3af2ea3b081442a054c4e3',
    messagingSenderId: '452055289306',
    projectId: 'babycare-86997',
    storageBucket: 'babycare-86997.appspot.com',
    iosBundleId: 'com.example.babycare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwKXGG0PFwYdr0N8iTWIcKzL726UfinxY',
    appId: '1:452055289306:web:8e87c87f4aced7b154c4e3',
    messagingSenderId: '452055289306',
    projectId: 'babycare-86997',
    authDomain: 'babycare-86997.firebaseapp.com',
    storageBucket: 'babycare-86997.appspot.com',
  );
}
